### ISSUE TITLE
Add ordered_list and button_list support

### ISSUE THREAD

**Issue by thejackshelton** [NordSecurity/storyblok-rich-text-astro-renderer#43]
Whenever I create an unordered list or ordered list inside my rich text it does not show up on my site. How can I add it? I've tried doing this:

```tsx
<RichTextRenderer
  content={text}
  schema={{
    nodes: {
      heading: ({ attrs: { level } }) => ({
        component: Text,
        props: { variant: `h${level}` },
      }),
      list_item: () => ({
        component: UL,
      }),
    },
  }}
  resolver={(blok) => {
    return {
      component: StoryblokComponent,
      props: { blok },
    };
  }}
  {...storyblokEditable(blok)}
/>
```

And then in UL.astro:
```tsx
---
const { ...props } = Astro.props;
---

<ul {...props}>
  <slot />
</ul>
```

Still no luck on getting it to show. When I change it to a heading or paragraph it shows up fine.

reproduction: https://stackblitz.com/edit/github-xvrhmy?file=src%2Fpages%2Findex.astro

## TODO

- Add ordered_list and button_list support

**Comment by edvinasjurele** [comment]
@thejackshelton Hi, Jack! thanks for noticing it 🙌 

I might not have been specific enough in the README of what is supported and what is not. I will make a table of supported and missing functionalities. Unfortunately, the `bullet_list` node is not supported yet!

I have started with basic nodes - `heading` / `paragraph` / `text` / `hard_break` (see in the [code](https://github.com/NordSecurity/storyblok-rich-text-astro-renderer/blob/main/lib/src/utils/resolveRichTextToNodes.ts)) - to be released initially and now I see a strong need to add the missing ones on-the-go!

**Comment by edvinasjurele** [comment]
@thejackshelton I have updated README https://github.com/NordSecurity/storyblok-rich-text-astro-renderer/pull/45

Working on this particular task to add `bullet_list` and `ordered_list` support!

**Comment by edvinasjurele** [comment]
@thejackshelton The missing functionality has been added 🎉 
Check demo now: https://stackblitz.com/github/NordSecurity/storyblok-rich-text-astro-renderer/tree/main/demo

And let me know if you encounter any issues.
